package com.example.webshop.business;

public enum Category {
    BLÄCKSVAMPAR, CHAMPINJONER, FJÄLLSKIVLINGAR, FLUGSVAMPAR, HAGVAXINGAR, KANTARELLER, KREMLOR, MURKLOR,
    MUSSERONER, MUSSLINGAR, PLUGGSKIVLINGAR, RISKOR, RÖKSVAMPAR, SAMMETSSOPPAR, SKOGSVAXINGAR, SLEMSKIVLINGAR, SLEMSOPPAR,
    SLÖJSKIVLINGAR, SPINDLINGAR, STRÄVSOPPAR, TAGGSVAMPAR, TICKOR, TOFSSKIVLINGAR, TRATTSKIVLINGAR, TRÅDINGAR,
    TRUMPETSVAMPAR, ÄDELSOPPAR, ÖVRIGA
}
